item {
  id: 1
  name: 'TOOL'
}

item {
  id: 2
  name: 'Wheel Brush'
}

item {
  id: 3
  name: 'Twist Brush-A'
}

item {
  id: 4
  name: 'Twist Brush-B'
}

item {
  id: 5
  name: 'C-PRODUCT'
}

item {
  id: 6
  name: 'D-PRODUCT'
}
